sonar.projectKey=finops-account-service
sonar.projectName=Finops Account Service
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=test
sonar.language=js
sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/db/index.js