replicaCount: 2

image:
  repository: transaction-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

config:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: finops
  DB_USER: finops_user
  PORT: "8000"

livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 15

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10